version: '3.8'

services:
  mosquitto:
    build:
      context: ./services/mosquitto
      dockerfile: Dockerfile
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"  # Optional: WebSockets MQTT Bridge
    volumes:
      - ./services/mosquitto/mosquitto_data:/mosquitto/data
      - ./services/mosquitto/mosquitto_config:/mosquitto/config
      - ./services/mosquitto/mosquitto_log:/mosquitto/log
    networks:
      - mqtt_network

  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - "1880:1880"  # Assuming Node-RED's default port is 1880
    volumes:
      - ./services/nodered/nodered_data:/data  # Mounting a volume for Node-RED data
    networks:
      - mqtt_network

networks:
  mqtt_network:
